apiVersion: v1
kind: Service
metadata:
  name: online-shop-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: online-shop # Perfectly links to the deployment labels above
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
